### ISSUE TITLE
sh picast_start.sh

### ISSUE THREAD

**Issue by vialonitasuhardiman** [lanceseidman/PiCAST#69]
I was using the Picast while loading the sh file this occured:rp@erp:~/PiCAST $ sh picast_start.sh
Starting PiCAST3...
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module 'express'
Require stack:
- /home/erp/PiCAST/picast.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/erp/PiCAST/picast.js:3:15)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/erp/PiCAST/picast.js' ]
}
and I haven't learn javascript so much so can somebody explain what this means,Thanks

**Comment by lanceseidman** [comment]
It's a bit outdated but perform an npm install in the directory OR type npm install express (if you have all other packages as global).
